"""extend_v2_templates_and_session_questions

Revision ID: 155ad1e4e41d
Revises: 5e59a010ec1e
Create Date: 2026-03-02 15:19:46.238148

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '155ad1e4e41d'
down_revision: Union[str, Sequence[str], None] = '5e59a010ec1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interview_session_questions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('interview_id', sa.Uuid(), nullable=False),
    sa.Column('question_id', sa.Uuid(), nullable=True),
    sa.Column('question_text', sa.String(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('time_limit_sec', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['interview_id'], ['interviews.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interview_session_questions_interview_id'), 'interview_session_questions', ['interview_id'], unique=False)
    op.add_column('interview_templates', sa.Column('is_rule_based', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('interview_templates', sa.Column('total_questions', sa.Integer(), nullable=True))
    op.add_column('interview_templates', sa.Column('difficulty_distribution', sa.JSON(), nullable=True))
    op.add_column('interview_templates', sa.Column('category_filters', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interview_templates', 'category_filters')
    op.drop_column('interview_templates', 'difficulty_distribution')
    op.drop_column('interview_templates', 'total_questions')
    op.drop_column('interview_templates', 'is_rule_based')
    op.drop_index(op.f('ix_interview_session_questions_interview_id'), table_name='interview_session_questions')
    op.drop_table('interview_session_questions')
    # ### end Alembic commands ###
