"""add_role_fields_to_template

Revision ID: 1dfa96dbbe22
Revises: 512b7bf918c5
Create Date: 2026-03-02 22:43:43.766417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1dfa96dbbe22'
down_revision: Union[str, Sequence[str], None] = '512b7bf918c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interview_templates', sa.Column('role_name', sa.String(), nullable=True))
    op.add_column('interview_templates', sa.Column('is_default_for_role', sa.Boolean(), server_default='false', nullable=False))
    op.alter_column('interview_templates', 'description',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.create_index(op.f('ix_interview_templates_role_name'), 'interview_templates', ['role_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_interview_templates_role_name'), table_name='interview_templates')
    op.alter_column('interview_templates', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('interview_templates', 'is_default_for_role')
    op.drop_column('interview_templates', 'role_name')
    # ### end Alembic commands ###
