"""add_resume_architecture_fields_to_candidateprofile

Revision ID: 3c21beef5d8f
Revises: 181a6b70edfd
Create Date: 2026-03-02 13:04:38.630792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c21beef5d8f'
down_revision: Union[str, Sequence[str], None] = '181a6b70edfd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidate_profiles', sa.Column('resume_filename', sa.String(), nullable=True))
    op.add_column('candidate_profiles', sa.Column('resume_path', sa.String(), nullable=True))
    op.add_column('candidate_profiles', sa.Column('resume_json', sa.JSON(), nullable=True))
    op.add_column('candidate_profiles', sa.Column('parse_status', sa.String(), nullable=False))
    op.add_column('candidate_profiles', sa.Column('parsed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidate_profiles', 'parsed_at')
    op.drop_column('candidate_profiles', 'parse_status')
    op.drop_column('candidate_profiles', 'resume_json')
    op.drop_column('candidate_profiles', 'resume_path')
    op.drop_column('candidate_profiles', 'resume_filename')
    # ### end Alembic commands ###
