"""create_interview_session_questions

Revision ID: 512b7bf918c5
Revises: 5e59a010ec1e
Create Date: 2026-03-02 21:33:54.256306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '512b7bf918c5'
down_revision: Union[str, Sequence[str], None] = '5e59a010ec1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interview_session_questions', sa.Column('custom_text', sa.Text(), nullable=True))
    op.drop_column('interview_session_questions', 'question_text')
    op.drop_column('interview_session_questions', 'time_limit_sec')
    op.drop_column('interview_templates', 'category_filters')
    op.drop_column('interview_templates', 'total_questions')
    op.drop_column('interview_templates', 'difficulty_distribution')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interview_templates', sa.Column('difficulty_distribution', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('interview_templates', sa.Column('total_questions', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('interview_templates', sa.Column('category_filters', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('interview_session_questions', sa.Column('time_limit_sec', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('interview_session_questions', sa.Column('question_text', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('interview_session_questions', 'custom_text')
    # ### end Alembic commands ###
