"""fresh_setup_with_use_alter

Revision ID: 67cf7f0cd608
Revises: 
Create Date: 2026-03-09 11:11:35.343256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67cf7f0cd608'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interview_templates',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('role_name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_default_for_role', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('settings', sa.JSON(), nullable=True),
    sa.Column('technical_config', sa.JSON(), nullable=True),
    sa.Column('coding_config', sa.JSON(), nullable=True),
    sa.Column('conversational_config', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interview_templates_role_name'), 'interview_templates', ['role_name'], unique=False)
    op.create_table('questions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('category', sa.Enum('PYTHON', 'SQL', 'MACHINE_LEARNING', 'DATA_STRUCTURES', 'SYSTEM_DESIGN', 'STATISTICS', name='categoryenum'), nullable=False),
    sa.Column('difficulty', sa.Enum('EASY', 'MEDIUM', 'HARD', name='difficultyenum'), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('question_type', sa.Enum('technical', 'behavioral', 'coding', name='questiontype'), server_default='technical', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'CANDIDATE', name='userrole'), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('login_disabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('admin_profiles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('department', sa.String(), nullable=True),
    sa.Column('designation', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('candidate_profiles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('role_name', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('resume_id', sa.String(), nullable=True),
    sa.Column('experience_years', sa.Integer(), nullable=True),
    sa.Column('skills', sa.JSON(), nullable=False),
    sa.Column('job_description', sa.String(), nullable=True),
    sa.Column('resume_text', sa.String(), nullable=True),
    sa.Column('resume_filename', sa.String(), nullable=True),
    sa.Column('resume_path', sa.String(), nullable=True),
    sa.Column('resume_json', sa.JSON(), nullable=True),
    sa.Column('jd_json', sa.JSON(), nullable=True),
    sa.Column('match_score', sa.Float(), nullable=True),
    sa.Column('parse_status', sa.String(), nullable=False),
    sa.Column('parsed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('face_verified', sa.Boolean(), nullable=False),
    sa.Column('voice_verified', sa.Boolean(), nullable=False),
    sa.Column('face_sample_url', sa.String(), nullable=True),
    sa.Column('video_sample_url', sa.String(), nullable=True),
    sa.Column('voice_sample_url', sa.String(), nullable=True),
    sa.Column('face_verification_id', sa.String(), nullable=True),
    sa.Column('voice_profile_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_candidate_profiles_role_name'), 'candidate_profiles', ['role_name'], unique=False)
    op.create_table('coding_problems',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('question_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('difficulty', sa.String(), nullable=False),
    sa.Column('starter_code', sa.JSON(), nullable=True),
    sa.Column('time_limit_sec', sa.Integer(), server_default='900', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('question_id')
    )
    op.create_table('interviews',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('candidate_id', sa.Uuid(), nullable=False),
    sa.Column('template_id', sa.Uuid(), nullable=True),
    sa.Column('assigned_by', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('SCHEDULED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', 'PENDING_REVIEW', name='interviewstatus'), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancellation_reason', sa.String(), nullable=True),
    sa.Column('overall_score', sa.Float(), nullable=True),
    sa.Column('feedback', sa.String(), nullable=True),
    sa.Column('curated_questions', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['candidate_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['interview_templates.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interviews_candidate_id'), 'interviews', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_interviews_scheduled_at'), 'interviews', ['scheduled_at'], unique=False)
    op.create_index(op.f('ix_interviews_status'), 'interviews', ['status'], unique=False)
    op.create_table('interview_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('interview_id', sa.Uuid(), nullable=False),
    sa.Column('candidate_id', sa.Uuid(), nullable=False),
    sa.Column('current_section_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('answered_count', sa.Integer(), nullable=False),
    sa.Column('face_verification_alerts', sa.Integer(), nullable=False),
    sa.Column('voice_verification_alerts', sa.Integer(), nullable=False),
    sa.Column('last_face_verification', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_voice_verification', sa.DateTime(timezone=True), nullable=True),
    sa.Column('termination_reason', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['interview_id'], ['interviews.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test_cases',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('problem_id', sa.Uuid(), nullable=False),
    sa.Column('input', sa.Text(), nullable=False),
    sa.Column('expected_output', sa.Text(), nullable=False),
    sa.Column('is_hidden', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['problem_id'], ['coding_problems.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('interview_session_sections',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('interview_session_id', sa.Uuid(), nullable=False),
    sa.Column('section_type', sa.String(length=50), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("section_type IN ('technical', 'coding', 'conversational')", name='check_section_type'),
    sa.CheckConstraint("status IN ('pending', 'in_progress', 'completed')", name='check_section_status'),
    sa.ForeignKeyConstraint(['interview_session_id'], ['interview_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interview_session_sections_interview_session_id'), 'interview_session_sections', ['interview_session_id'], unique=False)
    op.create_table('interview_session_questions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('interview_session_id', sa.Uuid(), nullable=False),
    sa.Column('section_id', sa.Uuid(), nullable=False),
    sa.Column('question_type', sa.String(length=20), nullable=False),
    sa.Column('question_id', sa.Uuid(), nullable=True),
    sa.Column('custom_text', sa.Text(), nullable=True),
    sa.Column('coding_problem_id', sa.Uuid(), nullable=True),
    sa.Column('conversation_round', sa.Integer(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(question_type = 'technical' AND question_id IS NOT NULL) OR (question_type = 'coding' AND coding_problem_id IS NOT NULL) OR (question_type = 'conversational' AND conversation_round IS NOT NULL) OR (custom_text IS NOT NULL)", name='check_question_payload'),
    sa.CheckConstraint("question_type IN ('technical', 'coding', 'conversational')", name='check_session_question_type'),
    sa.ForeignKeyConstraint(['coding_problem_id'], ['coding_problems.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['interview_session_id'], ['interview_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['section_id'], ['interview_session_sections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_session_section_order', 'interview_session_questions', ['interview_session_id', 'section_id', 'order'], unique=False)
    op.create_index(op.f('ix_interview_session_questions_interview_session_id'), 'interview_session_questions', ['interview_session_id'], unique=False)
    op.create_index(op.f('ix_interview_session_questions_section_id'), 'interview_session_questions', ['section_id'], unique=False)
    op.create_table('code_submissions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('problem_id', sa.Uuid(), nullable=False),
    sa.Column('interview_id', sa.Uuid(), nullable=False),
    sa.Column('candidate_id', sa.Uuid(), nullable=False),
    sa.Column('session_question_id', sa.Uuid(), nullable=True),
    sa.Column('language', sa.String(), nullable=False),
    sa.Column('source_code', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), server_default='pending', nullable=False),
    sa.Column('results', sa.JSON(), nullable=True),
    sa.Column('passed_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('total_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['interview_id'], ['interviews.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['problem_id'], ['coding_problems.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_question_id'], ['interview_session_questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('interview_responses',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('question_id', sa.Uuid(), nullable=False),
    sa.Column('answer_text', sa.Text(), nullable=True),
    sa.Column('answer_audio_url', sa.String(), nullable=True),
    sa.Column('answer_mode', sa.String(), nullable=False),
    sa.Column('ai_score', sa.Float(), nullable=True),
    sa.Column('ai_feedback', sa.Text(), nullable=True),
    sa.Column('evaluation_json', sa.JSON(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['interview_session_questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['interview_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interview_responses_session_id'), 'interview_responses', ['session_id'], unique=False)
    op.create_foreign_key('fk_session_current_section', 'interview_sessions', 'interview_session_sections', ['current_section_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_session_current_section', 'interview_sessions', type_='foreignkey')
    op.drop_index(op.f('ix_interview_responses_session_id'), table_name='interview_responses')
    op.drop_table('interview_responses')
    op.drop_table('code_submissions')
    op.drop_index(op.f('ix_interview_session_questions_section_id'), table_name='interview_session_questions')
    op.drop_index(op.f('ix_interview_session_questions_interview_session_id'), table_name='interview_session_questions')
    op.drop_index('idx_session_section_order', table_name='interview_session_questions')
    op.drop_table('interview_session_questions')
    op.drop_index(op.f('ix_interview_session_sections_interview_session_id'), table_name='interview_session_sections')
    op.drop_table('interview_session_sections')
    op.drop_table('test_cases')
    op.drop_table('interview_sessions')
    op.drop_index(op.f('ix_interviews_status'), table_name='interviews')
    op.drop_index(op.f('ix_interviews_scheduled_at'), table_name='interviews')
    op.drop_index(op.f('ix_interviews_candidate_id'), table_name='interviews')
    op.drop_table('interviews')
    op.drop_table('coding_problems')
    op.drop_index(op.f('ix_candidate_profiles_role_name'), table_name='candidate_profiles')
    op.drop_table('candidate_profiles')
    op.drop_table('admin_profiles')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_table('users')
    op.drop_table('questions')
    op.drop_index(op.f('ix_interview_templates_role_name'), table_name='interview_templates')
    op.drop_table('interview_templates')
    # ### end Alembic commands ###
