"""add_role_name_to_candidate_profile_final

Revision ID: 71b81e1ac664
Revises: 987f065bb27a
Create Date: 2026-03-02 23:19:04.562135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71b81e1ac664'
down_revision: Union[str, Sequence[str], None] = '987f065bb27a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidate_profiles', sa.Column('role_name', sa.String(), nullable=True))
    op.create_index(op.f('ix_candidate_profiles_role_name'), 'candidate_profiles', ['role_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_candidate_profiles_role_name'), table_name='candidate_profiles')
    op.drop_column('candidate_profiles', 'role_name')
    # ### end Alembic commands ###
