"""Add parsing fields to CandidateProfile

Revision ID: 85f04f485215
Revises: 3c21beef5d8f
Create Date: 2026-03-02 13:43:28.054463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85f04f485215'
down_revision: Union[str, Sequence[str], None] = '3c21beef5d8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidate_profiles', sa.Column('jd_json', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidate_profiles', 'jd_json')
    # ### end Alembic commands ###
