"""extend_interview_template_role_based

Revision ID: 987f065bb27a
Revises: 4734520fc8f4
Create Date: 2026-03-02 23:00:43.438490

"""
from typing import Sequence, Union
"""extend_interview_template_role_based

Revision ID: 987f065bb27a
Revises: 4734520fc8f4
Create Date: 2026-03-02 23:00:43.438490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '987f065bb27a'
down_revision: Union[str, Sequence[str], None] = '1dfa96dbbe22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('interview_templates', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('interview_templates', 'description',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###
