"""add_match_score_to_candidate_profile

Revision ID: b87cc7600014
Revises: 85f04f485215
Create Date: 2026-03-02 14:32:49.483283

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b87cc7600014'
down_revision: Union[str, Sequence[str], None] = '85f04f485215'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidate_profiles', sa.Column('match_score', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidate_profiles', 'match_score')
    # ### end Alembic commands ###
