"""
Interview Router — Admin-only scheduling endpoints (Refactored for SQLAlchemy)
----------------------------------------------------
POST   /admin/interviews/schedule          – Create a new scheduled interview
PUT    /admin/interviews/{id}/reschedule   – Move interview to a new datetime
PUT    /admin/interviews/{id}/cancel       – Cancel a non-completed interview
"""

import logging
import uuid
from fastapi import APIRouter, Depends, status, HTTPException, Query, Body
from sqlalchemy.ext.asyncio import AsyncSession
from typing import List, Optional

from sqlalchemy import select, func
from app.db.sql.models.interview_template import InterviewTemplate
from app.db.sql.models.coding_problem import CodingProblem
from app.db.sql.models.question import Question

from app.api.v1.auth_router import get_current_admin
from app.db.sql.session import get_db_session
from app.db.sql.models.user import User
from app.schemas.interview import (
    ScheduleInterviewRequest,
    ScheduleInterviewResponse,
    RescheduleInterviewRequest,
    RescheduleInterviewResponse,
    CancelInterviewRequest,
    CancelInterviewResponse,
)
from app.schemas.interview_template import TemplatePreviewResponse

logger = logging.getLogger(__name__)
from app.services.interview_admin_sql_service import InterviewAdminSQLService
from app.services.template_engine import template_engine
from app.db.sql.enums import InterviewStatus
from app.db.sql.unit_of_work import UnitOfWork

router = APIRouter()

def validate_uuid(id_str: str) -> uuid.UUID:
    try:
        return uuid.UUID(id_str)
    except ValueError:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=f"Invalid UUID: {id_str}",
        )

@router.get(
    "/templates",
    summary="List active interview templates",
    description="Admin-only. Returns all interview templates with is_active=True.",
)
async def list_templates(
    current_admin: User = Depends(get_current_admin),
    session: AsyncSession = Depends(get_db_session),
):
    return await InterviewAdminSQLService.list_active_templates(session)


@router.post(
    "/templates/{template_id}/preview",
    summary="Preview questions generated by a template",
    description="Admin-only. Generates and PERSISTS questions as a DRAFT interview if candidate_id is provided. If draft exists, returns it.",
)
async def preview_template(
    template_id: str,
    candidate_id: Optional[str] = Query(None),
    current_admin: User = Depends(get_current_admin),
    session: AsyncSession = Depends(get_db_session),
):
    validated_tid = validate_uuid(template_id)
    template = await session.get(InterviewTemplate, validated_tid)
    if not template:
        raise HTTPException(status_code=404, detail="Template not found")

    # If candidate_id is provided, manage DRAFT interview
    if candidate_id:
        validated_cid = validate_uuid(candidate_id)
        
        # 1. Check for existing DRAFT
        existing_draft = await InterviewAdminSQLService.get_draft_interview(session, validated_tid, validated_cid)
        if existing_draft:
            logger.info(f"Found existing DRAFT interview {existing_draft.id} for candidate {validated_cid}. Using cached questions.")
            curated = existing_draft.curated_questions or {}
            
            # Use the nested structure if available, fallback to flat 'questions'
            tech_section = curated.get('technical_section') or {"questions": curated.get('questions', [])}
            tech_questions = tech_section.get('questions', [])
            
            for q in tech_questions:
                if 'prompt' in q and 'text' not in q:
                    q['text'] = q['prompt']

            return {
                "interview_id": str(existing_draft.id),
                "technical_section": {"questions": tech_questions},
                "coding_section": curated.get("coding_section") or {"problems": (template.coding_config or {}).get("problems", [])},
                "conversational_section": curated.get("conversational_section") or {"rounds": (template.conversational_config or {}).get("rounds", 0)}
            }
        
        logger.info(f"No existing DRAFT found for candidate {validated_cid}. Generating NEW questions.")
        
        # 2. Generate new questions
        from app.services.question_generator_service import QuestionGeneratorService
        profile = None
        async with UnitOfWork(session) as uow:
            candidate = await uow.users.get_by_id(validated_cid)
            if candidate:
                profile = candidate.candidate_profile
            
        curated_questions = await QuestionGeneratorService.generate_curated_questions(
            session=session,
            template_id=template_id,
            candidate_id=candidate_id,
            resume_id=profile.resume_id if profile else None,
            resume_text=profile.resume_text if profile else "",
            job_description=profile.job_description if profile else "",
            resume_json=profile.resume_json if profile else None,
            jd_json=profile.jd_json if profile else None,
        )

        # Map 'prompt' to 'text' for frontend compatibility
        tech_section = curated_questions.get("technical_section") or {"questions": curated_questions.get("questions", [])}
        questions = tech_section.get("questions", [])
        for q in questions:
            if "prompt" in q and "text" not in q:
                q["text"] = q["prompt"]
        
        # 3. Save as DRAFT
        draft = await InterviewAdminSQLService.create_draft_interview(
            session=session,
            template_id=validated_tid,
            candidate_id=validated_cid,
            assigned_by=current_admin.id,
            curated_questions=curated_questions
        )
        await session.commit()
        logger.info(f"Successfully created and committed DRAFT interview {draft.id} for candidate {validated_cid}.")
        
        return {
            "interview_id": str(draft.id),
            "technical_section": {"questions": questions},
            "coding_section": curated_questions.get("coding_section") or {"problems": []},
            "conversational_section": curated_questions.get("conversational_section") or {"rounds": (template.conversational_config or {}).get("rounds", 0) if template else 0}
        }
        
    
    # Static preview if no candidate_id (legacy behavior/bank only)
    # ... (simplified or keep existing logic for non-candidate preview) ...
    return {"message": "Please provide candidate_id for a full draft preview"}


@router.post(
    "/{interview_id}/questions/{question_id}/regenerate",
    summary="Regenerate a single question in a draft interview",
)
async def regenerate_question(
    interview_id: str,
    question_id: str,
    comment: Optional[str] = Body(None, embed=True),
    current_admin: User = Depends(get_current_admin),
    session: AsyncSession = Depends(get_db_session),
):
    validated_iid = validate_uuid(interview_id)
    new_question = await InterviewAdminSQLService.regenerate_interview_question(
        session=session,
        interview_id=validated_iid,
        question_id=question_id,
        comment=comment
    )
    return new_question


@router.post(
    "/schedule",
    response_model=ScheduleInterviewResponse,
    status_code=status.HTTP_201_CREATED,
    summary="Schedule a new interview for a candidate",
)
async def schedule_interview(
    request: ScheduleInterviewRequest,
    current_admin: User = Depends(get_current_admin),
    session: AsyncSession = Depends(get_db_session),
):
    template_id = validate_uuid(request.template_id)
    candidate_id = validate_uuid(request.candidate_id)
    draft_interview_id = validate_uuid(request.draft_interview_id) if request.draft_interview_id else None
    
    interview = await InterviewAdminSQLService.create_interview(
        session=session,
        template_id=template_id,
        candidate_id=candidate_id,
        assigned_by=current_admin.id,
        scheduled_at=request.scheduled_at,
        questions=request.questions,
        draft_interview_id=draft_interview_id
    )
    
    return {
        "id": str(interview.id),
        "candidate_id": str(interview.candidate_id),
        "template_id": str(interview.template_id),
        "assigned_by": str(interview.assigned_by),
        "status": interview.status.value if isinstance(interview.status, InterviewStatus) else interview.status,
        "scheduled_at": interview.scheduled_at,
        "curated_questions": interview.curated_questions,
        "created_at": interview.created_at,
    }

@router.get(
    "/summary",
    summary="Get a lightweight summary of all interviews",
    description=(
        "Admin-only. Returns candidate_id, interview_id, status, and scheduled_at "
        "for every interview. Excludes curated_questions for performance."
    ),
)
async def get_interview_summary(
    limit: int = 10,
    offset: int = 0,
    search: str = "",
    current_admin: User = Depends(get_current_admin),
    session: AsyncSession = Depends(get_db_session),
):
    result = await InterviewAdminSQLService.get_interview_summary(session, limit, offset, search)
    data = [
        {
            "interview_id": str(s["interview_id"]),
            "candidate_id": str(s["candidate_id"]) if s["candidate_id"] else None,
            "status": s["status"].value if isinstance(s["status"], InterviewStatus) else s["status"],
            "scheduled_at": s["scheduled_at"],
            "overall_score": s.get("overall_score"),
        }
        for s in result["data"]
    ]
    return {
        "data": data,
        "total": result["total"],
        "limit": limit,
        "offset": offset
    }


@router.put(
    "/{interview_id}/reschedule",
    response_model=RescheduleInterviewResponse,
    status_code=status.HTTP_200_OK,
    summary="Reschedule an existing interview",
    description=(
        "Admin-only. Moves a 'scheduled' interview to a new future datetime. "
        "Returns 409 if status is anything other than 'scheduled'."
    ),
)
async def reschedule_interview(
    interview_id: str,
    request: RescheduleInterviewRequest,
    current_admin: User = Depends(get_current_admin),
    session: AsyncSession = Depends(get_db_session),
):
    validated_id = validate_uuid(interview_id)
    interview = await InterviewAdminSQLService.reschedule_interview(
        session=session,
        interview_id=validated_id,
        scheduled_at=request.scheduled_at,
    )
    
    return {
        "id": str(interview.id),
        "status": interview.status.value if isinstance(interview.status, InterviewStatus) else interview.status,
        "scheduled_at": interview.scheduled_at,
        "updated_at": interview.updated_at,
    }


@router.put(
    "/{interview_id}/cancel",
    response_model=CancelInterviewResponse,
    status_code=status.HTTP_200_OK,
    summary="Cancel an interview",
    description=(
        "Admin-only. Cancels an interview by setting status to 'cancelled'. "
        "The document is never deleted. Returns 409 if status is 'completed'."
    ),
)
async def cancel_interview(
    interview_id: str,
    request: CancelInterviewRequest = CancelInterviewRequest(),
    current_admin: User = Depends(get_current_admin),
    session: AsyncSession = Depends(get_db_session),
):
    validated_id = validate_uuid(interview_id)
    interview = await InterviewAdminSQLService.cancel_interview(
        session=session,
        interview_id=validated_id,
        reason=request.reason,
    )
    
    return {
        "id": str(interview.id),
        "status": interview.status.value if isinstance(interview.status, InterviewStatus) else interview.status,
        "cancelled_at": interview.cancelled_at,
        "reason": interview.cancellation_reason,
    }



@router.put(
    "/{interview_id}/questions",
    summary="Update questions for a scheduled or draft interview",
)
async def update_interview_questions(
    interview_id: str,
    questions: List[dict] = Body(...),
    current_admin: User = Depends(get_current_admin),
    session: AsyncSession = Depends(get_db_session),
):
    """Update questions for a scheduled or draft interview."""
    validated_id = validate_uuid(interview_id)
    
    async with UnitOfWork(session) as uow:
        interview = await uow.interviews.get_by_id(validated_id, with_for_update=True)
        
        if not interview:
            raise HTTPException(status_code=404, detail="Interview not found")
        
        if interview.status not in [InterviewStatus.SCHEDULED, InterviewStatus.DRAFT]:
            raise HTTPException(
                status_code=status.HTTP_400_BAD_REQUEST,
                detail="Can only update questions for scheduled or draft interviews"
            )
        
        # Reorder questions to ensure sequential order
        for idx, q in enumerate(questions, 1):
            q['order'] = idx
        
        if interview.curated_questions:
            interview.curated_questions['questions'] = questions
        else:
            interview.curated_questions = {
                "template_id": str(interview.template_id),
                "generated_from": {},
                "generated_at": datetime.utcnow().isoformat() + "Z",
                "generation_method": "manual_edit",
                "questions": questions
            }
        
        from sqlalchemy.orm.attributes import flag_modified
        flag_modified(interview, "curated_questions")
        await uow.flush()
        
        return {"message": "Questions updated successfully", "questions": questions}
